"use client";
import { use, useEffect, useState } from "react";
import Link from "next/link";
type Context={id:string;title:string;startsAt:string|null;objectives:string|null;agendaItems:string[];desiredOutcome:string|null};
type Note={id:string;rawText:string|null;revision:number;meetingContextId:string|null};
export default function ScratchpadPage({params}:{params:Promise<{id:string}>}) {
 const {id:organizationId}=use(params); const [note,setNote]=useState<Note|null>(null); const [text,setText]=useState(""); const [contexts,setContexts]=useState<Context[]>([]); const [contextId,setContextId]=useState(""); const [title,setTitle]=useState(""); const [status,setStatus]=useState("Saved"); const [offline,setOffline]=useState(false);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{ const cached=localStorage.getItem(`flowstate-scratchpad-${organizationId}`); if(cached) setText(cached); fetch(`/api/scratchpad?organizationId=${organizationId}`).then(r=>r.ok?r.json():[]).then((rows:Note[])=>{if(rows[0]){setNote(rows[0]); if(!cached)setText(rows[0].rawText??"");}}); fetch(`/api/meeting-contexts?organizationId=${organizationId}`).then(r=>r.ok?r.json():null).then((v:Context[])=>setContexts(Array.isArray(v)?v:[])); },[organizationId]);
 async function save(next:string){ localStorage.setItem(`flowstate-scratchpad-${organizationId}`,next); setStatus("Saving"); try { const res=await fetch("/api/scratchpad",{method:note?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(note?{id:note.id,text:next,revision:note.revision,contextId:contextId||null}:{organizationId,text:next,contextId:contextId||null})}); if(res.status===409){setStatus("Sync Failed");return;} if(!res.ok)throw new Error(); const saved=await res.json(); setNote(saved); setStatus("Saved"); setOffline(false); } catch { setOffline(true); setStatus("Offline"); } }
 function input(next:string){setText(next); void save(next);}
 return <main className="mx-auto max-w-4xl p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><Link href={`/clients/${organizationId}/capture`} className="text-sm text-[var(--muted)]">← Capture Evidence</Link><h1 className="mt-2 text-2xl font-bold">Meeting Day Scratch Pad</h1><p className="text-sm text-[var(--muted)]">Fast, freeform capture. Notes remain raw and reviewable.</p></div><span role="status" className="rounded-full border border-[var(--card-border)] px-3 py-1 text-xs">{offline?"Offline":status}</span></div><section className="workspace-card mb-4 p-4"><h2 className="font-semibold">Meeting context <span className="text-xs font-normal text-[var(--muted)]">(optional)</span></h2><input aria-label="Meeting title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Meeting title" className="mt-3 w-full rounded border border-[var(--card-border)] bg-transparent p-2"/><select aria-label="Meeting context" value={contextId} onChange={e=>setContextId(e.target.value)} className="mt-2 w-full rounded border border-[var(--card-border)] bg-transparent p-2"><option value="">No context / start capturing now</option>{contexts.map(c=><option key={c.id} value={c.id}>{c.title||new Date(c.startsAt ?? "").toLocaleString()}</option>)}</select></section><section className="workspace-card p-4"><div className="mb-2 flex gap-2"><button type="button" onClick={()=>input(text+"**bold**")} className="rounded border px-2 py-1 text-sm">Bold</button><button type="button" onClick={()=>input(text+"__underline__")} className="rounded border px-2 py-1 text-sm">Underline</button><button type="button" disabled className="rounded border px-2 py-1 text-sm opacity-60" title="Audio storage is not configured">Voice unavailable</button></div><textarea aria-label="Scratch pad note" autoFocus value={text} onChange={e=>input(e.target.value)} placeholder="Type or paste notes… Markdown is supported." rows={16} className="w-full resize-y rounded border border-[var(--card-border)] bg-transparent p-3 font-mono text-sm"/><p className="mt-2 text-xs text-[var(--muted)]">Autosaves every input event. {offline?"Changes are stored locally and will retry when connectivity returns.":"Raw evidence is kept separate from derived tags and decisions."}</p></section></main>;
}
