// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI/migration commands need a direct (non-pooled) connection: pgbouncer
    // transaction pooling on DATABASE_URL doesn't support the advisory locks
    // Migrate uses. The app's runtime PrismaClient uses DATABASE_URL (pooled)
    // separately via the adapter pattern in lib/db/index.ts.
    url: process.env["DIRECT_URL"],
  },
});
