"use client";

import { useEffect, useState } from "react";

type Item = { id: string; title: string; status: string; completionNote: string | null; linkedInput: { id: string; sourcePath: string | null; sourceRef: string | null } | null };
type Pack = { id: string; title: string; assessmentTask: { title: string; status: string; dueDate: string }; progress: { total: number; applicable: number; partiallyReceived: number; received: number; accepted: number; followUpRequired: number; fulfilmentPercent: number; reviewPercent: number }; categories: Array<{ id: string; title: string; requests: Item[] }> };
const statuses = ["REQUESTED", "PARTIALLY_RECEIVED", "RECEIVED", "ACCEPTED", "FOLLOW_UP_REQUIRED", "NOT_APPLICABLE"];
const label = (value: string) => value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function DataRoomPage({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState(""); const [packs, setPacks] = useState<Pack[]>([]); const [error, setError] = useState("");
  async function load(clientId: string) { const response = await fetch(`/api/clients/${clientId}/data-room`); const body = await response.json(); if (response.ok) setPacks(body); else setError(body.error ?? "Unable to load data room requests"); }
  useEffect(() => { params.then(({ id: clientId }) => { setId(clientId); void load(clientId); }); }, [params]);
  async function update(item: Item, status: string) { const note = status === "NOT_APPLICABLE" ? window.prompt("Why is this request not applicable?") : item.completionNote; if (status === "NOT_APPLICABLE" && !note) return; const response = await fetch(`/api/clients/${id}/data-room`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestId: item.id, status, completionNote: note }) }); const body = await response.json(); if (!response.ok) setError(body.error ?? "Unable to update request"); else void load(id); }
  return <main className="max-w-5xl mx-auto w-full px-4 py-8"><div className="mb-8"><div className="workspace-eyebrow mb-2">Assessment operations</div><h1 className="workspace-heading text-3xl font-bold">Data room requests</h1><p className="text-sm text-[var(--muted)] mt-2">Grouped diligence evidence requests. Receipt and review are tracked separately.</p></div>{error ? <p role="alert" className="text-[var(--destructive)]">{error}</p> : null}{packs.length === 0 ? <section className="workspace-card p-5">No Data Room Request Pack has been created for this client.</section> : packs.map((pack) => <section key={pack.id} className="workspace-card p-5 mb-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{pack.title}</h2><p className="text-sm text-[var(--muted)]">Assessment task: {pack.assessmentTask.title}</p></div><div className="text-sm"><strong>{pack.progress.fulfilmentPercent}% received</strong> · {pack.progress.received}/{pack.progress.applicable} applicable<br/><strong>{pack.progress.reviewPercent}% reviewed</strong> · {pack.progress.accepted}/{pack.progress.received} received{pack.progress.partiallyReceived ? ` · ${pack.progress.partiallyReceived} partial` : ""}</div></div><div className="mt-5 space-y-3">{pack.categories.map((category) => <details key={category.id} className="rounded-lg border border-[var(--border)] p-3"><summary className="cursor-pointer font-medium">{category.title} <span className="text-[var(--muted)]">({category.requests.filter((item) => item.status === "RECEIVED" || item.status === "ACCEPTED").length}/{category.requests.filter((item) => item.status !== "NOT_APPLICABLE").length} received)</span></summary><ul className="mt-3 space-y-3">{category.requests.map((item) => <li key={item.id} className="flex flex-wrap gap-3 justify-between border-t border-[var(--border)] pt-3"><div className="max-w-2xl"><p>{item.title}</p>{item.linkedInput ? <a className="text-sm underline" href={`/clients/${id}/documents/${item.linkedInput.id}`}>View linked evidence</a> : null}</div><label className="text-sm">Status <select aria-label={`Status for ${item.title}`} className="dashboard-input ml-2 p-1" value={item.status} onChange={(event) => void update(item, event.target.value)}>{statuses.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select></label></li>)}</ul></details>)}</div></section>)}</main>;
}
