import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { createClient } from "@/lib/supabase/server";
import { hasOrganizationPermission } from "@/lib/auth/organization";
import { displayLabel } from "@/lib/ui/display-label";
const transitions: Record<string, Record<string, string>> = { DRAFT: { SUBMIT: "READY_FOR_REVIEW" }, CHANGES_REQUESTED: { SUBMIT: "READY_FOR_REVIEW" }, READY_FOR_REVIEW: { REQUEST_CHANGES: "CHANGES_REQUESTED", APPROVE: "APPROVED_FOR_DISTRIBUTION" }, APPROVED_FOR_DISTRIBUTION: { ACKNOWLEDGE: "ACKNOWLEDGED" } };
async function auth(id: string) { const x = (await (await createClient()).auth.getUser()).data.user; if (!x?.email) return { response: NextResponse.json({ error: "Unauthorized" }, { status: 401 }) }; if (!(await hasOrganizationPermission(x.email, id, "assessment.review"))) return { response: NextResponse.json({ error: "Forbidden" }, { status: 403 }) }; return { email: x.email }; }
async function find(id: string, packId: string) { return prisma.communicationPack.findFirst({ where: { id: packId, organizationId: id }, include: { acknowledgements: { orderBy: { createdAt: "asc" } }, decision: true, insight: true } }); }
export async function GET(_request: NextRequest, { params }: { params: Promise<{ id: string; packId: string }> }) { const { id, packId } = await params; const result = await auth(id); if (result.response) return result.response; const pack = await find(id, packId); if (!pack) return NextResponse.json({ error: "Not found" }, { status: 404 }); return NextResponse.json({ ...pack, statusLabel: displayLabel(pack.status) }); }
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string; packId: string }> }) { const { id, packId } = await params; const result = await auth(id); if (result.response) return result.response; const pack = await find(id, packId); if (!pack) return NextResponse.json({ error: "Not found" }, { status: 404 }); const body = await request.json();
  const action = typeof body.action === "string" ? body.action : null; const next = action ? transitions[pack.status]?.[action] : undefined;
  if (action && !next) return NextResponse.json({ error: `Invalid transition from ${displayLabel(pack.status)}` }, { status: 409 });
  const editable = ["DRAFT", "CHANGES_REQUESTED"].includes(pack.status);
  const fields = editable && !action ? { ...(typeof body.title === "string" ? { title: body.title.trim() } : {}), ...(typeof body.content === "string" ? { content: body.content.trim() } : {}), ...(body.recipientContext ? { recipientContext: body.recipientContext } : {}), ...(body.stakeholderContext ? { stakeholderContext: body.stakeholderContext } : {}) } : {};
  const updated = await prisma.$transaction(async (tx) => { const saved = await tx.communicationPack.update({ where: { id: pack.id }, data: { ...fields, ...(next ? { status: next, reviewedBy: result.email, reviewedAt: new Date() } : {}) } as unknown as Parameters<typeof prisma.communicationPack.update>[0]["data"] }); if (action) await tx.communicationPackAcknowledgement.create({ data: { communicationPackId: pack.id, action: action === "SUBMIT" ? "SUBMITTED" : action === "APPROVE" ? "APPROVED" : action === "REQUEST_CHANGES" ? "REQUEST_CHANGES" : "ACKNOWLEDGED", note: typeof body.note === "string" ? body.note : null, actedBy: result.email! } }); return saved; });
  return NextResponse.json(await find(id, updated.id));
}
