import { afterAll, describe, expect, it, vi } from "vitest";
import { cleanupOrganization, createTestOrganization, prisma } from "../helpers/db";
const currentEmail = "advisor@test.com";
vi.mock("@/lib/supabase/server", () => ({ createClient: async () => ({ auth: { getUser: async () => ({ data: { user: { email: currentEmail } } }) } }) }));
import { POST as createRun, GET as listRuns } from "../../app/api/clients/[id]/agent-runs/route";
import { POST as createOutput } from "../../app/api/agent-runs/[id]/output/route";
describe("governed agent run and provisional output contract", () => {
  let organizationId = ""; let foreignOrganizationId = ""; let inputId = "";
  afterAll(async () => { if (organizationId) await cleanupOrganization(organizationId); if (foreignOrganizationId) await prisma.organization.delete({ where: { id: foreignOrganizationId } }); await prisma.agentDefinition.deleteMany({ where: { key: { startsWith: "run-contract-agent-" } } }); await prisma.$disconnect(); });
  it("creates a pending run only for an authorised organisation and snapshots the published prompt", async () => {
    const organization = await createTestOrganization({ name: "Agent Run Contract Org" }); organizationId = organization.id; const foreign = await prisma.organization.create({ data: { name: "Agent Run Foreign Org" } }); foreignOrganizationId = foreign.id;
    const admin = await prisma.user.create({ data: { email: `run-admin-${Date.now()}@flowstate.test`, role: "SYSTEM_ADMIN" } });
    const agent = await prisma.agentDefinition.create({ data: { key: `run-contract-agent-${Date.now()}`, name: "Evidence reviewer", createdBy: admin.email, promptVersions: { create: { version: 1, prompt: "Review evidence only.", changeReason: "Initial", authoredBy: admin.email } } }, include: { promptVersions: true } }); await prisma.agentDefinition.update({ where: { id: agent.id }, data: { publishedPromptVersionId: agent.promptVersions[0].id } });
    const input = await prisma.capturedInput.create({ data: { organizationId, type: "TEXT_NOTE", rawText: "Approved source evidence", status: "TRANSCRIBED" } }); inputId = input.id;
    const response = await createRun(new Request("http://localhost/api/clients/run/agent-runs", { method: "POST", body: JSON.stringify({ capturedInputId: input.id, agentDefinitionId: agent.id }) }), { params: Promise.resolve({ id: organizationId }) }); expect(response.status).toBe(201); const body = await response.json(); expect(body.run).toMatchObject({ organizationId, capturedInputId: input.id, agentDefinitionId: agent.id, promptVersionId: agent.promptVersions[0].id, status: "PENDING" }); expect(body.run.output).toBeNull();
    const forbidden = await createRun(new Request("http://localhost/api/clients/run/agent-runs", { method: "POST", body: JSON.stringify({ capturedInputId: input.id, agentDefinitionId: agent.id }) }), { params: Promise.resolve({ id: foreignOrganizationId }) }); expect(forbidden.status).toBe(403);
  });
  it("stores explicit provider output as provisional and never approves it", async () => { const run = await prisma.agentRun.findFirstOrThrow({ where: { capturedInputId: inputId } }); const response = await createOutput(new Request(`http://localhost/api/agent-runs/${run.id}/output`, { method: "POST", body: JSON.stringify({ provisionalOutput: { summary: "Human-review candidate" }, provider: "unconfigured", model: "not-called" }) }), { params: Promise.resolve({ id: run.id }) }); expect(response.status).toBe(201); const body = await response.json(); expect(body.output).toMatchObject({ runId: run.id, status: "PROVISIONAL", provisionalOutput: { summary: "Human-review candidate" }, provider: "unconfigured", model: "not-called", reviewedBy: null, reviewedAt: null }); expect((await prisma.agentRun.findUniqueOrThrow({ where: { id: run.id } })).status).toBe("OUTPUT_READY"); });
  it("lists runs within the requested organisation only", async () => { const response = await listRuns(new Request(`http://localhost/api/clients/${organizationId}/agent-runs`), { params: Promise.resolve({ id: organizationId }) }); expect(response.status).toBe(200); expect((await response.json()).runs).toHaveLength(1); });
});
