import { afterAll, describe, expect, it, vi } from "vitest";
import { cleanupOrganization, createTestOrganization, prisma } from "../helpers/db";
vi.mock("@/lib/supabase/server", () => ({ createClient: async () => ({ auth: { getUser: async () => ({ data: { user: { email: "advisor@test.com" } } }) } }) }));
import { POST } from "../../app/api/clients/[id]/communication-packs/route";
import { GET, PATCH } from "../../app/api/clients/[id]/communication-packs/[packId]/route";
const req = (body: unknown, method = "POST") => new Request("http://test", { method, body: JSON.stringify(body), headers: { "Content-Type": "application/json" } });
describe("communication pack authorization and review persistence", () => {
 let org = "", other = "", decision = "", pack = "";
 afterAll(async () => { if (org) await cleanupOrganization(org); if (other) await cleanupOrganization(other); await prisma.$disconnect(); });
 it("creates from an approved in-organisation decision and preserves the source", async () => {
  const a = await createTestOrganization({ name: "Pack Org" }); org = a.id; const domain = await prisma.businessDomain.create({ data: { organizationId: org, name: "Operations" } }); const capability = await prisma.capability.create({ data: { domainId: domain.id, name: "Planning" } }); const d = await prisma.assessmentDecision.create({ data: { capabilityId: capability.id, status: "SIGNED_OFF", score: 3, rationale: "Keep unchanged" } }); decision = d.id;
  const response = await POST(req({ title: "Update", content: "Approved message", decisionId: decision, recipientContext: { audience: "Board" }, stakeholderContext: { owner: "CFO" } }) as never, { params: Promise.resolve({ id: org }) });
  expect(response.status).toBe(201); const body = await response.json(); pack = body.id; expect(body.status).toBe("DRAFT"); const unchanged = await prisma.assessmentDecision.findUnique({ where: { id: decision } }); expect(unchanged?.rationale).toBe("Keep unchanged");
 });
 it("rejects a source from another organisation", async () => { const b = await createTestOrganization({ name: "Other Pack Org" }); other = b.id; const domain = await prisma.businessDomain.create({ data: { organizationId: other, name: "Other" } }); const capability = await prisma.capability.create({ data: { domainId: domain.id, name: "Other capability" } }); const d = await prisma.assessmentDecision.create({ data: { capabilityId: capability.id, status: "APPROVED" } }); const response = await POST(req({ title: "No", content: "No", decisionId: d.id, recipientContext: {}, stakeholderContext: {} }) as never, { params: Promise.resolve({ id: org }) }); expect(response.status).toBe(400); });
 it("enforces transitions and appends history", async () => { let response = await PATCH(req({ action: "SUBMIT" }, "PATCH") as never, { params: Promise.resolve({ id: org, packId: pack }) }); expect(response.status).toBe(200); response = await PATCH(req({ action: "REQUEST_CHANGES", note: "Please clarify" }, "PATCH") as never, { params: Promise.resolve({ id: org, packId: pack }) }); expect(response.status).toBe(200); const body = await response.json(); expect(body.status).toBe("CHANGES_REQUESTED"); expect(body.acknowledgements).toHaveLength(2); response = await PATCH(req({ action: "APPROVE" }, "PATCH") as never, { params: Promise.resolve({ id: org, packId: pack }) }); expect(response.status).toBe(409); const detail = await GET(new Request("http://test") as never, { params: Promise.resolve({ id: org, packId: pack }) }); expect((await detail.json()).statusLabel).toBe("Changes Requested"); });
});
