-- AlterTable
ALTER TABLE "Capability" ALTER COLUMN "aliases" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "dimensions" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "metrics" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "opportunities" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "weaknesses" SET DEFAULT ARRAY[]::TEXT[];
