"use client";
import { useEffect, useState } from "react";
import { displayLabel } from "@/lib/ui/display-label";

type History = { action: string; note?: string | null; actedBy: string; createdAt: string };
type Pack = { id: string; title: string; content: string; status: string; recipientContext: unknown; stakeholderContext: unknown; decision?: { id: string; status: string; rationale?: string | null } | null; insight?: { id: string; title: string; status: string } | null; acknowledgements: History[] };
type QueueResponse = { packs: Pack[]; summary: Record<string, number>; sources?: { decisions: { id: string; status: string; label: string }[]; insights: { id: string; title: string; status: string }[] } };
const text = (value: unknown) => typeof value === "string" ? value : JSON.stringify(value, null, 2);

export default function Page({ params }: { params: Promise<{ id: string }> }) {
  const [orgId, setOrgId] = useState(""), [packs, setPacks] = useState<Pack[]>([]), [summary, setSummary] = useState<Record<string, number>>({}), [selected, setSelected] = useState<Pack | null>(null), [status, setStatus] = useState(""), [recipient, setRecipient] = useState(""), [stakeholder, setStakeholder] = useState(""), [note, setNote] = useState(""), [decisionId, setDecisionId] = useState(""), [insightId, setInsightId] = useState(""), [title, setTitle] = useState(""), [sources, setSources] = useState<{ decisions: { id: string; status: string; label: string }[]; insights: { id: string; title: string; status: string }[] }>({ decisions: [], insights: [] }), [content, setContent] = useState(""), [message, setMessage] = useState("");
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { params.then(({ id }) => { setOrgId(id); void load(id); }); }, [params]);
  async function load(id = orgId) { const query = new URLSearchParams({ ...(status ? { status } : {}), ...(recipient ? { recipient } : {}), ...(stakeholder ? { stakeholder } : {}) }); const response = await fetch(`/api/clients/${id}/communication-packs?${query}`); if (!response.ok) { setMessage("Unable to load review queue"); return; } const body = await response.json() as QueueResponse; setPacks(body.packs ?? []); setSummary(body.summary ?? {}); setSources(body.sources ?? { decisions: [], insights: [] }); }
  async function open(pack: Pack) { const response = await fetch(`/api/clients/${orgId}/communication-packs/${pack.id}`); if (response.ok) setSelected(await response.json() as Pack); }
  async function saveDraft(event: React.FormEvent) { event.preventDefault(); const response = await fetch(`/api/clients/${orgId}/communication-packs`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, content, decisionId: decisionId || undefined, insightId: insightId || undefined, recipientContext: { recipient }, stakeholderContext: { stakeholder } }) }); if (!response.ok) { const body = await response.json(); setMessage(body.error ?? "Unable to save draft"); return; } setTitle(""); setContent(""); setDecisionId(""); setInsightId(""); setMessage("Draft saved"); await load(); }
  async function review(action: "ACKNOWLEDGE" | "REQUEST_CHANGES") { if (!selected) return; setMessage(""); const response = await fetch(`/api/clients/${orgId}/communication-packs/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, note }) }); const body = await response.json(); if (!response.ok) { setMessage(body.error ?? "Unable to update pack"); return; } setSelected(body); setNote(""); setMessage(action === "ACKNOWLEDGE" ? "Pack acknowledged" : "Changes requested"); await load(); }
  return <main className="max-w-6xl mx-auto w-full px-4 py-8"><h1 className="workspace-heading text-3xl font-bold">Communication pack review queue</h1><p className="text-sm text-[var(--muted)] mt-2 mb-6">Review approved stakeholder updates. Nothing is sent externally.</p>
    <form onSubmit={saveDraft} className="workspace-card p-4 grid gap-3 mb-4" aria-label="Create communication pack"><input required placeholder="Title" className="dashboard-input px-3 py-2" value={title} onChange={e => setTitle(e.target.value)} /><textarea required placeholder="Approved content" className="dashboard-input px-3 py-2" value={content} onChange={e => setContent(e.target.value)} /><select aria-label="Approved assessment decision" className="dashboard-input px-3 py-2" value={decisionId} onChange={e => setDecisionId(e.target.value)}><option value="">No approved decision source</option>{sources.decisions.map(decision => <option key={decision.id} value={decision.id}>{decision.label} — {displayLabel(decision.status)}</option>)}</select><select aria-label="Approved insight" className="dashboard-input px-3 py-2" value={insightId} onChange={e => setInsightId(e.target.value)}><option value="">No approved insight source</option>{sources.insights.map(source => <option key={source.id} value={source.id}>{source.title} — {displayLabel(source.status)}</option>)}</select><p className="text-sm text-[var(--muted)]">At least one approved source is required. No approved decision sources available or No approved insight sources available.</p><button className="dashboard-primary-button px-4 py-2 w-fit">Save draft</button></form>
    <section className="workspace-card p-4 grid gap-3 md:grid-cols-4" aria-label="Queue filters"><select aria-label="Filter by status" className="dashboard-input px-3 py-2" value={status} onChange={e => { setStatus(e.target.value); }}><option value="">All statuses</option>{Object.keys(summary).map(value => <option key={value} value={value}>{displayLabel(value)}</option>)}</select><input aria-label="Filter by recipient" placeholder="Recipient" className="dashboard-input px-3 py-2" value={recipient} onChange={e => setRecipient(e.target.value)} /><input aria-label="Filter by stakeholder" placeholder="Stakeholder" className="dashboard-input px-3 py-2" value={stakeholder} onChange={e => setStakeholder(e.target.value)} /><button className="dashboard-primary-button px-4 py-2" onClick={() => void load()}>Apply filters</button><div className="md:col-span-4 flex flex-wrap gap-3 text-sm" aria-label="Status summary">{Object.entries(summary).map(([value, count]) => <span key={value}>{displayLabel(value)}: <strong>{count}</strong></span>)}</div></section>
    <div className="grid gap-4 mt-4 lg:grid-cols-[1fr_1.2fr]"> <section aria-label="Review queue">{packs.length === 0 ? <p className="workspace-card p-5">No communication packs match these filters.</p> : packs.map(pack => <button key={pack.id} className="workspace-card p-5 mb-3 w-full text-left" onClick={() => void open(pack)}><div className="flex justify-between gap-3"><h2 className="font-semibold">{pack.title}</h2><span>{displayLabel(pack.status)}</span></div><p className="text-sm text-[var(--muted)] mt-2">Recipient: {text(pack.recipientContext)}</p><p className="text-sm text-[var(--muted)]">Stakeholder: {text(pack.stakeholderContext)}</p></button>)}</section>
      {selected && <article className="workspace-card p-5" aria-label="Communication pack detail"><h2 className="text-xl font-semibold">{selected.title}</h2><p className="mt-2"><strong>Status:</strong> {displayLabel(selected.status)}</p><h3 className="font-semibold mt-4">Recipient context</h3><pre className="text-sm whitespace-pre-wrap">{text(selected.recipientContext)}</pre><h3 className="font-semibold mt-4">Stakeholder context</h3><pre className="text-sm whitespace-pre-wrap">{text(selected.stakeholderContext)}</pre><h3 className="font-semibold mt-4">Approved source references</h3>{selected.decision && <p className="text-sm">Decision {selected.decision.id}: {displayLabel(selected.decision.status)}</p>}{selected.insight && <p className="text-sm">Insight {selected.insight.id}: {selected.insight.title} ({displayLabel(selected.insight.status)})</p>}<h3 className="font-semibold mt-4">Approved pack content</h3><p className="whitespace-pre-wrap">{selected.content}</p><h3 className="font-semibold mt-4">Review history</h3>{selected.acknowledgements.length ? <ol className="text-sm space-y-2">{selected.acknowledgements.map((item, index) => <li key={`${item.createdAt}-${index}`}><strong>{displayLabel(item.action)}</strong> by {item.actedBy}{item.note ? ` — ${item.note}` : ""}</li>)}</ol> : <p className="text-sm">No review actions yet.</p>}{selected.status === "READY_FOR_REVIEW" && <div className="mt-5 grid gap-3"><textarea aria-label="Review comment" placeholder="Comment (required for request changes)" className="dashboard-input px-3 py-2" value={note} onChange={e => setNote(e.target.value)} /><div className="flex gap-2"><button className="dashboard-primary-button px-4 py-2" onClick={() => void review("ACKNOWLEDGE")}>Acknowledge</button><button className="dashboard-secondary-button px-4 py-2" onClick={() => void review("REQUEST_CHANGES")}>Request changes</button></div></div>}</article>}</div>{message && <p role="status" className="mt-3">{message}</p>}</main>;
}
