"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { ThemeToggle } from "@/components/layout/ThemeToggle";

type InputType = "AUDIO" | "TEXT_NOTE" | "EMAIL" | "DOCUMENT" | "DATA_ROOM_FILE";
type Version = { id: string; version: number; prompt: string; changeReason: string; authoredBy: string; createdAt: string; publishedAt: string | null; publishedBy: string | null };
type Rule = { id?: string; inputType: InputType; domainIdentifier: string };
type Agent = { id: string; key: string; name: string; description: string | null; createdBy: string; createdAt: string; promptVersions: Version[]; inputRules: Rule[]; publishedPromptVersion: Version | null };

const inputTypes: InputType[] = ["TEXT_NOTE", "AUDIO", "EMAIL", "DOCUMENT", "DATA_ROOM_FILE"];
const labels: Record<InputType, string> = { TEXT_NOTE: "Text note", AUDIO: "Audio", EMAIL: "Email", DOCUMENT: "Document", DATA_ROOM_FILE: "Data room file" };
const date = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not published";

export default function AgentCataloguePage() {
  const router = useRouter();
  const [agents, setAgents] = useState<Agent[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ key: "", name: "", description: "", prompt: "", changeReason: "" });
  const [rules, setRules] = useState<Rule[]>([{ inputType: "TEXT_NOTE", domainIdentifier: "" }]);
  const [versionPrompt, setVersionPrompt] = useState("");
  const [versionReason, setVersionReason] = useState("");

  async function load() {
    setLoading(true); setError("");
    try { const response = await fetch("/api/admin/agents"); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to load agent catalogue"); setAgents(data.agents ?? []); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load agent catalogue"); } finally { setLoading(false); }
  }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);

  const selected = agents.find((agent) => agent.id === selectedId) ?? null;
  const drafts = selected?.promptVersions.filter((version) => version.id !== selected.publishedPromptVersion?.id) ?? [];
  function setRule(index: number, patch: Partial<Rule>) { setRules((current) => current.map((rule, i) => i === index ? { ...rule, ...patch } : rule)); }
  function resetForm() { setForm({ key: "", name: "", description: "", prompt: "", changeReason: "" }); setRules([{ inputType: "TEXT_NOTE", domainIdentifier: "" }]); }
  async function createAgent(event: FormEvent) {
    event.preventDefault(); setSaving(true); setError("");
    try { const response = await fetch("/api/admin/agents", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, inputRules: rules.filter((rule) => rule.domainIdentifier.trim()) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to create agent"); setAgents((current) => [...current, data.agent].sort((a, b) => a.name.localeCompare(b.name))); setSelectedId(data.agent.id); setCreating(false); resetForm(); setNotice("Agent created as a draft. Publish a prompt version after review."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to create agent"); } finally { setSaving(false); }
  }
  async function addVersion(event: FormEvent) {
    event.preventDefault(); if (!selected) return; setSaving(true); setError("");
    try { const response = await fetch(`/api/admin/agents/${selected.id}/versions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt: versionPrompt, changeReason: versionReason }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to save prompt version"); setVersionPrompt(""); setVersionReason(""); setNotice(`Version ${data.version.version} saved as a draft.`); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save prompt version"); } finally { setSaving(false); }
  }
  async function publish(version: Version) {
    if (!selected || !window.confirm(`Publish version ${version.version} for ${selected.name}? This will become the active prompt.`)) return; setSaving(true); setError("");
    try { const response = await fetch(`/api/admin/agents/${selected.id}/publish`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ versionId: version.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to publish version"); setAgents((current) => current.map((agent) => agent.id === selected.id ? data.agent : agent)); setNotice(`Version ${version.version} is now published.`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to publish version"); } finally { setSaving(false); }
  }
  async function signOut() { await createClient().auth.signOut(); router.push("/auth/login"); router.refresh(); }

  return <div className="admin-shell">
    <aside className="admin-rail"><div className="admin-rail-header"><Link href="/dashboard" className="workspace-brand"><span className="workspace-brand-mark" aria-hidden="true">FS</span><span className="workspace-brand-name">Flowstate</span></Link></div><div className="admin-context"><div className="workspace-context-label">Platform control</div><div className="workspace-context-name">Administration</div></div><nav className="workspace-nav" aria-label="Platform navigation"><Link href="/admin" className="workspace-nav-link"><span className="workspace-nav-icon" aria-hidden="true">01</span>Administration</Link><Link href="/admin/agents" aria-current="page" className="workspace-nav-link"><span className="workspace-nav-icon" aria-hidden="true">02</span>Agent catalogue</Link><Link href="/dashboard" className="workspace-nav-link"><span className="workspace-nav-icon" aria-hidden="true">03</span>Client workspaces</Link></nav><div className="admin-rail-actions"><ThemeToggle /><button type="button" className="workspace-signout" onClick={signOut}>Sign out</button></div></aside>
    <main className="admin-content"><header className="admin-header"><div><div className="workspace-eyebrow">Platform control centre</div><h1 className="workspace-heading admin-title">Agent catalogue</h1><p className="admin-subtitle">Review prompt versions and input boundaries before making an agent active.</p></div><div className="admin-status"><span className="admin-status-dot" aria-hidden="true" /> System administrator</div></header>
      {error && <div role="alert" className="admin-alert">{error}</div>}{notice && <div role="status" className="agent-notice">{notice}</div>}
      <div className="agent-toolbar"><div><div className="workspace-eyebrow">Global agents</div><p className="agent-count">{loading ? "Loading…" : `${agents.length} agent${agents.length === 1 ? "" : "s"}`}</p></div><button type="button" className="agent-primary-button" onClick={() => { resetForm(); setCreating(true); }}>+ Create agent</button></div>
      {loading ? <div className="workspace-card admin-loading" role="status">Loading agent catalogue…</div> : agents.length === 0 ? <div className="workspace-card agent-empty"><h2>No agents yet</h2><p>Create the first catalogue entry to define a reviewed prompt and safe input scope.</p><button type="button" className="agent-primary-button" onClick={() => { resetForm(); setCreating(true); }}>Create agent</button></div> : <div className="agent-layout"><section className="agent-list" aria-label="Agents">{agents.map((agent) => <button type="button" key={agent.id} className={`workspace-card agent-list-item ${selected?.id === agent.id ? "is-selected" : ""}`} onClick={() => setSelectedId(agent.id)}><span className="agent-list-name">{agent.name}</span><span className="agent-list-key">{agent.key}</span><span className={`agent-state ${agent.publishedPromptVersion ? "is-published" : "is-draft"}`}>{agent.publishedPromptVersion ? `Published v${agent.publishedPromptVersion.version}` : "No published prompt"}</span></button>)}</section>
        {selected && <section className="workspace-card agent-detail" aria-labelledby="agent-detail-title"><div className="agent-detail-header"><div><div className="workspace-eyebrow">Agent definition</div><h2 id="agent-detail-title" className="workspace-heading agent-detail-title">{selected.name}</h2><p className="agent-description">{selected.description || "No description provided."}</p></div><span className="agent-key">{selected.key}</span></div>
          <div className="agent-section"><div className="agent-section-heading"><h3>Published prompt</h3><span className="agent-state is-published">Active</span></div>{selected.publishedPromptVersion ? <div className="agent-published"><p>{selected.publishedPromptVersion.prompt}</p><small>Version {selected.publishedPromptVersion.version} · Published {date(selected.publishedPromptVersion.publishedAt)} by {selected.publishedPromptVersion.publishedBy ?? "unknown"}</small></div> : <p className="agent-muted">No prompt is active. Drafts remain inactive until explicitly published.</p>}</div>
          <div className="agent-section"><div className="agent-section-heading"><h3>Draft prompt versions</h3><span>{drafts.length}</span></div>{drafts.length ? <div className="agent-version-stack">{drafts.map((version) => <article className="agent-version agent-draft" key={version.id}><div><strong>Version {version.version}</strong><p>{version.prompt}</p><small>Reason: {version.changeReason} · Authored {date(version.createdAt)} by {version.authoredBy}</small></div><button type="button" className="agent-secondary-button" disabled={saving} onClick={() => void publish(version)}>Publish version</button></article>)}</div> : <p className="agent-muted">No unpublished versions.</p>}</div>
          <form className="agent-section agent-form" onSubmit={addVersion}><h3>Add prompt version</h3><label htmlFor="version-prompt">Prompt<textarea id="version-prompt" required value={versionPrompt} onChange={(event) => setVersionPrompt(event.target.value)} placeholder="Write a bounded prompt for human review…" /></label><label htmlFor="version-reason">Change reason<textarea id="version-reason" required value={versionReason} onChange={(event) => setVersionReason(event.target.value)} placeholder="Why is this change needed?" /></label><button type="submit" className="agent-primary-button" disabled={saving}>{saving ? "Saving…" : "Save draft version"}</button></form>
          <div className="agent-section"><div className="agent-section-heading"><h3>Input boundaries</h3><span>{selected.inputRules.length} rules</span></div>{selected.inputRules.length ? <ul className="agent-rule-list">{selected.inputRules.map((rule) => <li key={rule.id ?? `${rule.inputType}-${rule.domainIdentifier}`}><span>{labels[rule.inputType]}</span><code>{rule.domainIdentifier}</code></li>)}</ul> : <p className="agent-muted">No input rules configured.</p>}<p className="agent-help">Input rules are bounded to approved types and domain identifiers. Update them when creating a new catalogue entry.</p></div>
          <details className="agent-section agent-history"><summary>Version history ({selected.promptVersions.length})</summary><div className="agent-history-list">{[...selected.promptVersions].sort((a, b) => b.version - a.version).map((version) => <div key={version.id}><strong>Version {version.version}</strong><span>{version.publishedAt ? `Published ${date(version.publishedAt)} by ${version.publishedBy}` : `Draft · Authored ${date(version.createdAt)} by ${version.authoredBy}`}</span><p>{version.changeReason}</p></div>)}</div></details>
        </section>}</div>}
      {creating && <div className="agent-modal-backdrop" role="presentation"><section className="workspace-card agent-modal" role="dialog" aria-modal="true" aria-labelledby="create-agent-title"><div className="agent-modal-heading"><h2 id="create-agent-title">Create agent</h2><button type="button" className="agent-close" aria-label="Close create agent dialog" onClick={() => setCreating(false)}>×</button></div><form className="agent-form" onSubmit={createAgent}><label htmlFor="agent-key">Key<input id="agent-key" required pattern="[a-z0-9-]+" value={form.key} onChange={(event) => setForm({ ...form, key: event.target.value })} /></label><label htmlFor="agent-name">Name<input id="agent-name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label htmlFor="agent-description">Description<textarea id="agent-description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label htmlFor="agent-prompt">Initial prompt<textarea id="agent-prompt" required value={form.prompt} onChange={(event) => setForm({ ...form, prompt: event.target.value })} /></label><label htmlFor="agent-reason">Change reason<textarea id="agent-reason" required value={form.changeReason} onChange={(event) => setForm({ ...form, changeReason: event.target.value })} /></label><fieldset><legend>Input boundaries</legend>{rules.map((rule, index) => <div className="agent-rule-editor" key={index}><label htmlFor={`rule-type-${index}`}>Input type<select id={`rule-type-${index}`} value={rule.inputType} onChange={(event) => setRule(index, { inputType: event.target.value as InputType })}>{inputTypes.map((type) => <option key={type} value={type}>{labels[type]}</option>)}</select></label><label htmlFor={`rule-domain-${index}`}>Domain identifier<input id={`rule-domain-${index}`} required pattern="[a-zA-Z0-9._-]+" value={rule.domainIdentifier} onChange={(event) => setRule(index, { domainIdentifier: event.target.value })} /></label>{rules.length > 1 && <button type="button" className="agent-remove" onClick={() => setRules((current) => current.filter((_, i) => i !== index))}>Remove</button>}</div>)}<button type="button" className="agent-link-button" onClick={() => setRules((current) => [...current, { inputType: "TEXT_NOTE", domainIdentifier: "" }])}>+ Add input rule</button></fieldset><div className="agent-modal-actions"><button type="button" className="agent-secondary-button" onClick={() => setCreating(false)}>Cancel</button><button type="submit" className="agent-primary-button" disabled={saving}>{saving ? "Creating…" : "Create agent"}</button></div></form></section></div>}
    </main></div>;
}
